// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glsnkextimhtzmukfxno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdsc25rZXh0aW1odHptdWtmeG5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzgyNzEsImV4cCI6MjA2NzY1NDI3MX0.df3FTZZvKG5RYLGi0MFpom0BNgqirTh6WYkER7xZOfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});